# Generated by Django 6.0.6 on 2026-06-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_unique_email'),
        ('causes', '0002_phase4_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_cause',
            field=models.ForeignKey(blank=True, help_text='Causa que el usuario apoya por defecto; se preselecciona al pagar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_by', to='causes.cause'),
        ),
    ]
