# Generated by Django 6.0.3 on 2026-04-06 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0001_initial'),
        ('causes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbacktransaction',
            name='cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='causes.cause'),
        ),
        migrations.CreateModel(
            name='UserCauseAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_allocations', to='causes.cause')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cause_allocations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'cause')},
            },
        ),
    ]
