# Generated by Django 5.2.5 on 2026-04-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0002_add_usercauseallocation_and_cause_fk'),
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='selected_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='causes.cause'),
        ),
    ]
