# Generated by Django 5.2.5 on 2026-04-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0003_purchase_selected_cause'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCauseAllocation',
        ),
    ]
