# Generated by Django 6.0.3 on 2026-04-06 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0005_campaign_refactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='campaignstore',
            name='cashback_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override del porcentaje global de la campaña para esta tienda. Null = usar global.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
