# Generated by Django 6.0.5 on 2026-06-08 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashback', '0006_percentage_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPPaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_id', models.CharField(blank=True, max_length=200, verbose_name='MP Preference ID')),
                ('checkout_url', models.URLField(blank=True, max_length=500, verbose_name='URL de checkout MP')),
                ('mp_payment_id', models.CharField(blank=True, max_length=100, verbose_name='MP Payment ID')),
                ('mp_status', models.CharField(choices=[('INITIATED', 'Iniciado'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado'), ('PENDING', 'Pendiente'), ('CANCELLED', 'Cancelado')], default='INITIATED', max_length=20, verbose_name='Estado MP')),
                ('mp_status_detail', models.CharField(blank=True, max_length=200, verbose_name='Detalle de estado MP')),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monto pagado en MP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mp_payment', to='cashback.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Pago Mercado Pago',
                'verbose_name_plural': 'Pagos Mercado Pago',
            },
        ),
    ]
