# Generated by Django 5.2.5 on 2026-04-06 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
        ('commerce', '0002_category_store_active_store_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSupportedCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_stores', to='causes.cause')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supported_causes', to='commerce.store')),
            ],
            options={
                'unique_together': {('store', 'cause')},
            },
        ),
    ]
