# Generated by Django 5.2.5 on 2026-04-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cause',
            name='cashback_percent',
        ),
    ]
